#!/usr/bin/env python3
"""Add bespoke execution instructions to high-consequence Project-MSR v4.3 work packages.

The general migration gives every activity a consistent implementation record. This
script replaces the generic execution sequence for the work packages that govern
fuel, salt chemistry, fission-product behavior, source term, materials, safeguards,
startup and commercial scaling.

The instructions intentionally define evidence, facilities, measurements, gates and
records without prescribing an operational recipe for enrichment, fissile-material
separation or unrestricted reprocessing. Uranium-bearing and irradiated work remains
limited to authorized facilities and approved procedures.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, Iterable, List, Mapping, MutableMapping, Sequence

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_DB = ROOT / "data" / "project_msr_database.full.json"


def step(
    step_id: str,
    action: str,
    responsible_role: str,
    supporting_roles: Sequence[str],
    work_location: str,
    required_inputs: Sequence[str],
    detailed_guidance: str,
    tools_equipment: Sequence[str],
    outputs_and_records: Sequence[str],
    acceptance_condition: str,
    hold_point: str,
) -> Dict[str, Any]:
    return {
        "step_id": step_id,
        "action": action,
        "responsible_role": responsible_role,
        "supporting_roles": list(supporting_roles),
        "work_location": work_location,
        "required_inputs": list(required_inputs),
        "detailed_guidance": detailed_guidance,
        "tools_equipment": list(tools_equipment),
        "outputs_and_records": list(outputs_and_records),
        "acceptance_condition": acceptance_condition,
        "hold_point": hold_point,
    }


def decision(decision_text: str, owner: str, required_by: str, evidence: str) -> Dict[str, str]:
    return {"decision": decision_text, "owner": owner, "required_by": required_by, "evidence": evidence}


def field(activity: str, where: str, evidence: str) -> Dict[str, str]:
    return {"activity": activity, "where": where, "evidence": evidence}


def open_decision(decision_text: str, owner: str, required_by: str, closure_evidence: str) -> Dict[str, str]:
    return {
        "decision": decision_text,
        "owner": owner,
        "required_by": required_by,
        "closure_evidence": closure_evidence,
    }


def all_tasks(db: Mapping[str, Any]) -> Iterable[MutableMapping[str, Any]]:
    yield from db.get("tasks", [])
    for module in db.get("pathway_modules", {}).values():
        yield from module.get("demonstrator", [])
        yield from module.get("power_reactor", [])


def find_task(db: Mapping[str, Any], task_id: str) -> MutableMapping[str, Any]:
    for task in all_tasks(db):
        if str(task.get("id")) == task_id:
            return task
    raise KeyError(task_id)


def update_plan(task: MutableMapping[str, Any], **updates: Any) -> None:
    plan = task.setdefault("implementation_plan", {})
    plan.update(updates)
    plan["implementation_readiness"] = "Task-specific execution sequence, facility work, decision gates, acceptance evidence, records, and fallback routes are defined for the current planning basis."
    plan["implementation_quality_score"] = 100


def common_roles() -> List[str]:
    return ["Fuel/Materials Engineer", "Radiation Protection/Chemistry", "Data/Software Engineer"]


def apply(db: MutableMapping[str, Any]) -> None:
    # Methods/topical report integrating chemistry, properties, source term and off-gas.
    t = find_task(db, "S-MTH-04")
    update_plan(
        t,
        implementation_summary=(
            "Qualify the chemistry, property, fission-product, source-term and off-gas methods as one controlled methods package: "
            "define the phenomena and data needs, execute the 25-test evidence ladder, fit correlations with covariance and conditions of use, "
            "perform blind validation against integral and irradiated data, and issue the topical report and code/model release used by design and licensing."
        ),
        delivery_strategy={
            "owner_scope": "Project engineers retain requirements ownership, code-of-record methods, data acceptance, safety/licensing conclusions and topical-report authorship.",
            "external_scope": "Qualified laboratories and national-laboratory partners execute bounded chemistry, hot-cell, irradiation and off-gas work packages with native data, sample custody, uncertainty and review deliverables.",
            "preferred_contract_form": "Fixed-scope technical work orders with staged readiness, interim data, draft report and final qualified-data releases.",
            "work_location_strategy": "Use nonradioactive commercial or university facilities first; use DOE/national-laboratory authorized facilities for uranium-bearing or irradiated work."
        },
        implementation_steps=[
            step("MTH-CHEM-01", "Freeze the phenomena, figures of merit, decisions and validation requirements.", "Fuel/Materials Engineer", common_roles(), "Project methods organization", ["design-basis salt envelope", "PIRT and event list", "source-term species groups", "materials and processing architecture"], "Create a requirements-to-evidence matrix covering feed acceptance, purification, synthesis, phase behavior, thermophysical properties, redox, corrosion, fission-product partitioning, off-gas, sampling, online sensors, processing, waste and MC&A. For each item define the model parameter, range, target uncertainty, test source, acceptance rule and downstream design/licensing owner.", ["requirements database", "PIRT/validation matrix", "property and source-term model inventory"], ["approved methods requirements specification", "validation matrix", "data-gap and facility plan"], "Every safety-significant method input or model claim has a qualified data source or an approved conservative treatment and closure plan.", "HP-MC1 methods requirements freeze"),
            step("MTH-CHEM-02", "Qualify source data, sample genealogy and analytical methods.", "Radiation Protection/Chemistry", ["Fuel/Materials Engineer", "QA/Configuration Management", "Data/Software Engineer"], "Qualified chemistry and analytical laboratories", ["CHEM-01 to CHEM-07 protocols", "reference materials", "laboratory quality plans", "sample/archive plan"], "Approve analytical methods, calibrations, blanks, standards, replicate rules, detection limits, uncertainty budgets, sample custody and interlaboratory checks before crediting data. Maintain raw native data, instrument configuration and sample genealogy in the evidence repository.", ["ICP-MS/OES or equivalent", "ion chromatography", "oxygen/moisture analysis", "electrochemical methods", "XRD/Raman as applicable", "LIMS/EDMS"], ["analytical method qualification reports", "reference-material results", "laboratory applicability assessments", "qualified sample registry"], "Decision-significant measurements meet the target uncertainty, reproducibility and traceability requirements and have an independent cross-check.", "HP-MC2 analytical methods qualified"),
            step("MTH-CHEM-03", "Execute the separate-effects and engineering-scale chemistry/property campaigns.", "Fuel/Materials Engineer", common_roles(), "Qualified bench and engineering-scale salt facilities", ["approved test matrix", "material/salt lots", "calibrated equipment", "pre-test predictions"], "Execute CHEM-02 through CHEM-21 in staged order, beginning with stable nonradioactive salts and surrogates. Record as-tested composition, temperature, atmosphere, contact materials, flow, deposits, samples and exceptions. Do not proceed to uranium-bearing or irradiated work until the surrogate result shows that the configuration, measurement method and waste route are ready.", ["controlled-atmosphere preparation systems", "property measurement equipment", "corrosion loops/capsules", "off-gas and capture testbeds", "time-synchronized DAQ"], ["qualified datasets", "material and sample balances", "test reports", "exception dispositions", "retained samples"], "Each dataset is independently reviewed, uncertainty-qualified and accepted for its stated range or assigned a corrective/retest action.", "HP-MC3 separate-effects evidence accepted"),
            step("MTH-CHEM-04", "Fit correlations and mechanistic submodels with quantified uncertainty.", "Data/Software Engineer", ["Fuel/Materials Engineer", "Radiation Protection/Chemistry", "Safety Analysis Engineer"], "Project methods organization", ["qualified chemistry/property datasets", "model equations", "code QA plan", "conditions of use"], "Fit composition- and temperature-dependent property correlations, redox/impurity response, corrosion/mass-transfer, gas transfer, aerosol/deposition, capture and release submodels. Preserve covariance and model-form uncertainty; reject overfitting by holding back validation data and documenting extrapolation limits.", ["Python/R or equivalent qualified analysis workflow", "RAVEN or equivalent UQ", "code repository and CI", "statistical diagnostics"], ["controlled correlation library", "covariance/uncertainty package", "model implementation and regression tests", "conditions-of-use register"], "Correlation residuals, uncertainty and physical behavior satisfy preapproved criteria over the credited domain; limitations are explicit and enforced in code/model use.", "HP-MC4 model/correlation release"),
            step("MTH-CHEM-05", "Perform blind integral and irradiated validation.", "Safety Analysis Engineer", ["Fuel/Materials Engineer", "Radiation Protection/Chemistry", "Data/Software Engineer"], "ITHF, INL experiment and demonstrator evidence teams", ["frozen pre-test predictions", "qualified ITHF/INL/demonstrator data", "measurement uncertainty", "validation metrics"], "Freeze predictions before data release, compare time histories and integral balances, calculate validation metrics, and investigate discrepancies. Use CHEM-22 and CHEM-23 only in authorized radiation facilities and use CHEM-24 demonstrator data to confirm coupled nuclear/thermal/chemical behavior.", ["code-of-record models", "validation metric scripts", "qualified data repository", "configuration comparison tools"], ["blind comparison reports", "discrepancy records", "updated uncertainty/conditions of use", "model validation report"], "All high-ranked phenomena are validated or bounded with an approved limitation, and discrepancies that affect safety margins or processing design are closed before final topical release.", "HP-MC5 integral validation accepted"),
            step("MTH-CHEM-06", "Issue the topical report and controlled production release.", "Licensing Engineer", ["Fuel/Materials Engineer", "Safety Analysis Engineer", "QA/Configuration Management", "Data/Software Engineer"], "Project licensing and methods organization", ["validated methods", "software QA evidence", "conditions of use", "regulatory engagement record"], "Assemble theory, equations, data pedigree, validation matrix, uncertainty, software implementation, user guidance, limitations and sample applications. Conduct independent technical review, licensing consistency review and pre-submittal readiness assessment; maintain an RAI-ready electronic evidence index.", ["controlled authoring system", "EDMS", "requirements traceability", "code release repository"], ["topical report", "software/model release note", "user and model-development guidance", "evidence index", "regulatory response plan"], "The report and code release are reproducible, traceable to qualified data, internally approved and suitable for design/licensing use within explicit conditions of applicability.", "HP-MC6 topical report release")
        ],
        decision_points=[
            decision("Chemistry/property/source-term method scope and credited domain", "Methods lead/design authority", "2027-03-31", "approved methods requirements and validation matrix"),
            decision("Data adequate for correlation and model release", "Chemistry/methods/independent review", "2028-06-30", "qualified datasets and model-fit review"),
            decision("Integral and irradiated validation adequate for final topical", "Methods/licensing/design authority", "2030-12-31", "blind validation report and discrepancy closure"),
        ],
        field_lab_or_vendor_activities=[
            field("Chemistry/property/separate-effects testing", "Qualified commercial, university or national-laboratory facilities", "approved work orders, procedures, raw data, calibration, sample custody and reports"),
            field("Irradiated-salt/hot-cell confirmation", "Authorized DOE/national-laboratory radiological facility", "authorization, sample transfer, analysis, waste and data-release records"),
        ],
        open_decisions=[
            open_decision("Final salt family and composition envelope", "Chemistry/physics/design authority", "2027-03-31", "approved fuel and chemistry requirements"),
            open_decision("Lead laboratories and interlaboratory round-robin participants", "Chemistry lead/procurement/QA", "2027-06-30", "facility qualification and executed work orders"),
        ],
        task_specific_test_ids=[f"CHEM-{i:02d}" for i in range(1, 26)],
    )

    # Thermophysical property database.
    t = find_task(db, "S-MSR-02")
    update_plan(
        t,
        implementation_summary="Produce the controlled salt property database used by design and safety analysis from independently verified composition, phase and property measurements; quantify correlations, covariance, extrapolation limits and batch-to-batch uncertainty; and release machine-readable and report forms under configuration control.",
        implementation_steps=[
            step("PROP-01", "Freeze compositions, operating ranges, properties and target uncertainties.", "Fuel/Materials Engineer", common_roles(), "Project chemistry/methods organization", ["candidate fuel/carrier salt compositions", "normal/transient temperature ranges", "TH/structural/source-term model needs", "manufacturing impurity envelope"], "Create a design-of-experiments matrix that spans nominal, manufacturing tolerance, burnup/chemistry drift and bounding impurity conditions. Define the minimum measurements for density, viscosity, heat capacity, thermal conductivity/diffusivity, phase transitions, vapor/volatility and any model-specific property.", ["property-needs matrix", "DOE/statistical design tools", "requirements database"], ["approved property measurement plan", "composition/temperature matrix", "uncertainty targets"], "All consuming models identify the property, domain, units, interpolation rule and uncertainty they require.", "HP-P1 property scope freeze"),
            step("PROP-02", "Prepare and independently characterize representative salt batches.", "Radiation Protection/Chemistry", ["Fuel/Materials Engineer", "QA/Configuration Management"], "Qualified preparation and analytical laboratory", ["approved batch recipes under authorized procedure", "qualified feed lots", "sample/retention plan", "atmosphere controls"], "Prepare traceable batches for each matrix point, verify composition and impurities before property testing, retain reference samples, and document thermal history and any observed segregation or precipitation. Uranium-bearing samples are prepared only in an authorized facility.", ["controlled-atmosphere preparation equipment", "qualified analytical methods", "LIMS/EDMS"], ["batch travelers", "certificates and independent analyses", "retained sample registry", "as-prepared composition uncertainty"], "Batch composition, homogeneity and impurity vector meet the test specification and are reconciled to starting material and samples.", "HP-P2 batches accepted"),
            step("PROP-03", "Measure phase behavior and thermophysical properties with replicate and reference checks.", "Fuel/Materials Engineer", ["Radiation Protection/Chemistry", "Data/Software Engineer", "Independent Reviewer"], "Qualified property laboratories", ["accepted batches", "calibrated property instruments", "reference materials", "preapproved uncertainty budgets"], "Execute CHEM-04 and CHEM-05 with at least duplicate independent measurements for acceptance-critical properties, reference-fluid/material checks, heat/cool cycles to identify hysteresis, and interlaboratory checks for the most important correlations.", ["DSC/DTA or equivalent", "density/viscosity apparatus", "thermal diffusivity/conductivity equipment", "vapor/volatility apparatus where needed", "calibration standards"], ["raw measurements", "calibration/reference results", "replicate analysis", "interlaboratory comparison", "qualified property dataset"], "Measurement uncertainty and reproducibility meet preapproved targets; phase/segregation anomalies are understood and bounded.", "HP-P3 property data qualified"),
            step("PROP-04", "Fit correlations, covariance and uncertainty models.", "Data/Software Engineer", ["Fuel/Materials Engineer", "Thermal-Hydraulics Engineer", "Safety Analysis Engineer"], "Project data/methods organization", ["qualified data", "composition metadata", "measurement covariance", "physical constraints"], "Fit transparent physically consistent correlations, retain raw data and residuals, quantify parameter covariance and model-form uncertainty, compare alternative fits, reserve validation points, and define interpolation/extrapolation behavior.", ["qualified Python/R workflow", "RAVEN or equivalent UQ", "unit and physical-consistency tests", "version control/CI"], ["correlation coefficients and covariance", "fit/validation report", "machine-readable property library", "conditions-of-use file"], "Fits satisfy statistical and physical checks over the credited domain and do not silently extrapolate outside it.", "HP-P4 correlation release"),
            step("PROP-05", "Integrate, verify and release the property database.", "Thermal-Hydraulics Engineer", ["Data/Software Engineer", "Fuel/Materials Engineer", "QA/Configuration Management"], "Project analysis organization", ["released correlation library", "code interfaces", "gold cases", "downstream model input specifications"], "Implement the same controlled property source in system TH, CFD, heat transfer, structural, source-term and operations tools; run unit tests, cross-code consistency tests and sensitivity checks; issue both human-readable and machine-readable releases with change notification.", ["code repositories and CI", "gold-case regression suite", "data schema validators", "EDMS"], ["integrated property library", "cross-code verification report", "release note and user guide", "change-control baseline"], "All codes reproduce reference values within tolerance and downstream analyses identify the exact database version used.", "HP-P5 database production release")
        ],
        decision_points=[
            decision("Property matrix and uncertainty targets", "TH/chemistry/methods", "2027-03-31", "approved property measurement plan"),
            decision("Property database adequate for demonstrator design", "TH/chemistry/design authority", "2028-03-31", "demonstrator-ready release and validation report"),
            decision("Final commercial property release", "Methods/licensing/design authority", "2030-12-31", "integral/irradiated confirmation and final release"),
        ],
        task_specific_test_ids=["CHEM-01", "CHEM-03", "CHEM-04", "CHEM-05", "CHEM-22", "CHEM-23", "CHEM-24"],
    )

    # Mechanistic source term and fission-product transport.
    t = find_task(db, "S-MSR-04")
    update_plan(
        t,
        implementation_summary="Close a configuration-specific fission-product mass balance over fuel salt, cover gas, deposits, filters/sorbents, samples, processing residues, structures and releases; validate gas transfer, aerosol, volatile species, noble-metal plate-out and retention with surrogates, then confirm with irradiated and demonstrator data before releasing source-term parameters and uncertainty.",
        implementation_steps=[
            step("MST-01", "Define inventory, species groups, compartments, pathways and event conditions.", "Safety Analysis Engineer", ["Reactor Physicist", "Radiation Protection/Chemistry", "Fuel/Materials Engineer"], "Project source-term team", ["depletion/inventory vectors", "salt chemistry envelope", "system P&IDs and volumes", "event list and temperatures/flows"], "Define behavior groups for noble gases, volatile halogens, alkalis, noble metals, rare earths/actinides, aerosols and particulates. Map each group from generation to salt, gas, deposits, capture media, samples, processing waste, structures and releases for normal, transient and accident conditions.", ["inventory/depletion tools", "compartment/mass-balance model", "requirements database"], ["species-group basis", "compartment/pathway diagram", "initial inventory and uncertainty register", "test requirements"], "The model conserves total inventory and every credited retention/release mechanism has a data or conservative-bounding basis.", "HP-ST1 source-term architecture freeze"),
            step("MST-02", "Execute stable-surrogate gas-transfer, aerosol, capture and plate-out tests.", "Radiation Protection/Chemistry", ["Fuel/Materials Engineer", "Test/Commissioning Engineer", "Data/Software Engineer"], "Qualified salt/off-gas and materials facilities", ["CHEM-11 to CHEM-17 protocols", "representative geometry/flow/temperature", "surrogate selection technical basis", "pre-test model predictions"], "Run staged tests for speciation/solubility, stable noble-gas residence time, aerosol generation/transport/capture, volatile-halogen and alkali surrogate capture, noble-metal plate-out/resuspension and particulate filtration. Reconcile salt, gas, deposit, filter and sample inventories and repeat key conditions.", ["salt loop/off-gas analog", "gas analyzers and aerosol instruments", "deposition coupons", "filters/sorbents", "time-synchronized DAQ"], ["qualified CHEM-11 to CHEM-17 datasets", "mass balance", "deposit/filter characterization", "performance degradation and maintenance data"], "Mass-balance closure and measurement uncertainty are adequate to discriminate competing models and identify the minimum credited treatment functions.", "HP-ST2 surrogate evidence accepted"),
            step("MST-03", "Demonstrate the integrated processing/off-gas train and abnormal responses.", "Systems Engineer", ["Radiation Protection/Chemistry", "Fuel/Materials Engineer", "Operations Engineer", "Test/Commissioning Engineer"], "Engineering-scale process skid/ITHF analog", ["selected treatment architecture", "surrogate test results", "equipment specifications", "fault and maintenance scenarios"], "Execute CHEM-19 through CHEM-21 over repeated cycles, including startup/shutdown, bypass, filter/sorbent loading, sensor drift, controlled plugging/fouling precursors, sample withdrawal, component changeout and material-balance reconciliation. Capture performance decay and operator/maintenance burden.", ["integrated processing skid", "off-gas/capture system", "online sensors", "sampling equipment", "material-accountancy model"], ["integrated performance curves", "failure/maintenance data", "operating procedures", "as-tested P&IDs", "qualified mass balance"], "The selected treatment architecture meets its required decontamination/retention, reliability, maintainability and inventory-control functions without unacceptable salt loss or unresolved plugging/fouling risk.", "HP-ST3 architecture qualified"),
            step("MST-04", "Confirm surrogate assumptions with irradiated-salt and radiation-environment evidence.", "Radiation Protection/Chemistry", ["Safety Analysis Engineer", "Fuel/Materials Engineer", "INL/Host Interface Lead"], "Authorized INL/national-laboratory radiological facilities", ["CHEM-22/23 plans", "critical-experiment samples", "surrogate-model predictions", "sample transfer and waste authorization"], "Analyze irradiated samples, deposits, filters/sorbents and gas-train specimens under approved hot-cell/radiochemical procedures. Compare species partitioning, sensor/sorbent response, corrosion/deposition and material-accountancy signatures to surrogate predictions; do not infer separations performance beyond the authorized measurements.", ["hot-cell/sample analysis capability", "gamma/radiochemical analytical methods", "microscopy/surface analysis", "controlled data transfer"], ["irradiated confirmation dataset", "surrogate applicability assessment", "model discrepancy dispositions", "sample/waste closeout"], "Radiation and true fission-product effects are either confirmed within uncertainty or incorporated as conservative correction factors/conditions of use.", "HP-ST4 irradiated confirmation accepted"),
            step("MST-05", "Calibrate and validate the mechanistic source-term model.", "Safety Analysis Engineer", ["Data/Software Engineer", "Radiation Protection/Chemistry", "PRA Engineer"], "Project safety-analysis organization", ["qualified separate/integral/irradiated data", "event boundary conditions", "model-form alternatives", "uncertainty distributions"], "Fit physically based transfer/retention parameters, preserve correlations and uncertainty, perform blind comparisons against withheld and 2029 demonstrator data, calculate event-specific release fractions and timing, and quantify sensitivity to chemistry, temperature, flow, failure state and treatment availability.", ["MELCOR/MAAP or project source-term models as applicable", "RAVEN or equivalent UQ", "qualified Python analysis", "configuration control"], ["validated source-term model", "parameter/uncertainty database", "event release-category results", "conditions of use"], "Predicted compartment inventories and release metrics meet validation criteria or are conservatively bounded with approved limitations.", "HP-ST5 model validation release"),
            step("MST-06", "Issue design, licensing and operations source-term products.", "Licensing Engineer", ["Safety Analysis Engineer", "Radiation Protection/Chemistry", "Systems Engineer", "QA/Configuration Management"], "Project licensing/design organization", ["validated model", "system design and treatment availability", "licensing path requirements", "operating monitoring strategy"], "Release mechanistic source-term report/topical, design loads for shielding/confinement/off-gas, monitoring and sampling requirements, waste inventories, accident release inputs, PRA release categories and operator surveillance/action limits. Maintain a traceable evidence index and update triggers.", ["controlled authoring/EDMS", "requirements/traceability database", "model release repository"], ["mechanistic source-term report", "design input tables", "monitoring/surveillance requirements", "licensing application content", "update/operating feedback plan"], "All downstream products use one controlled source-term baseline, with explicit credited functions, uncertainty and change-control triggers.", "HP-ST6 source-term baseline issued")
        ],
        decision_points=[
            decision("Species grouping and credited retention/treatment functions", "Safety analysis/chemistry/design authority", "2027-06-30", "approved source-term architecture and test matrix"),
            decision("Minimum installed off-gas/processing architecture", "Systems/chemistry/safety/operations", "2027-12-31", "integrated processing down-select and hazards review"),
            decision("Source-term model adequate for commercial application", "Safety analysis/licensing/design authority", "2030-12-31", "irradiated/demonstrator validation and final report"),
        ],
        task_specific_test_ids=[f"CHEM-{i:02d}" for i in range(11, 25)],
    )

    # Instrumentation and sampling qualification.
    t = find_task(db, "S-MSR-05")
    update_plan(
        t,
        implementation_summary="Qualify online chemistry, redox, off-gas, level/flow/temperature and representative hot-sampling methods through calibration, high-temperature exposure, drift/fouling testing, cross-calibration to independent laboratory samples, failure detection, maintenance demonstrations and irradiation confirmation.",
        implementation_steps=[
            step("INST-01", "Define measurement functions, ranges, accuracy, response, location and maintainability.", "Instrumentation & Controls Engineer", ["Radiation Protection/Chemistry", "Fuel/Materials Engineer", "Operations Engineer"], "Project I&C/chemistry organization", ["chemistry control strategy", "source-term/MC&A needs", "system P&IDs", "environmental/radiation profiles"], "Create a measurement requirements matrix for redox, composition proxies, gas species, aerosol/particulate loading, mass/level/flow, sample representativeness and calibration checks. Define which measurements are control, protection, material-accountancy, diagnostic or confirmatory and the consequence of failure.", ["requirements database", "instrument location drawings", "uncertainty allocation worksheets"], ["measurement requirements specification", "instrument/sampling architecture", "uncertainty and maintenance targets"], "Every credited chemistry, source-term or MC&A function has a qualified measurement or conservative fallback and an accessible maintenance/calibration concept.", "HP-I1 measurement architecture freeze"),
            step("INST-02", "Bench-calibrate candidate sensors and sampling methods.", "Radiation Protection/Chemistry", ["Instrumentation & Controls Engineer", "Data/Software Engineer", "Independent Laboratory"], "Qualified chemistry/instrument laboratory", ["candidate devices", "reference standards", "calibration matrix", "sample/custody procedure"], "Execute CHEM-06 and CHEM-20 at controlled composition and temperature, compare online response and withdrawn samples to independent laboratory values, quantify lag, bias, repeatability, carryover, contamination and sample-location effects, and down-select candidates.", ["electrochemical/reference electrode systems", "gas analyzers", "sampling probes/valves", "reference standards", "independent analytical methods"], ["calibration curves and uncertainty", "sampling representativeness report", "candidate down-select", "failure-mode observations"], "Candidate methods meet accuracy/repeatability targets and the sampling method does not introduce a material bias or unacceptable material loss/exposure.", "HP-I2 bench down-select"),
            step("INST-03", "Expose instruments and sample systems to representative thermal, chemical and flow conditions.", "Instrumentation & Controls Engineer", ["Fuel/Materials Engineer", "Test/Commissioning Engineer", "Radiation Protection/Chemistry"], "Salt loop/ITHF and component test facilities", ["down-selected devices", "representative salt/cover gas", "thermal/flow/impurity profiles", "installation details"], "Run thermal cycling, long-duration immersion/exposure, flow, vibration, impurity perturbation and controlled deposit/fouling conditions. Track drift, response, insulation/seal behavior, reference stability, plugging and maintainability; execute removal, cleaning, recalibration and replacement evolutions.", ["salt loops/ITHF", "environmental and vibration test equipment", "portable reference instruments", "DAQ/historian"], ["drift/fouling curves", "environmental qualification evidence", "maintenance/replacement procedure", "as-installed constraints"], "Required mission duration and maintenance interval are demonstrated with adequate uncertainty and no unresolved common-mode failure.", "HP-I3 environmental qualification"),
            step("INST-04", "Qualify online/offline cross-calibration and failure detection.", "Data/Software Engineer", ["Instrumentation & Controls Engineer", "Radiation Protection/Chemistry", "Operations Engineer"], "Integrated chemistry/processing skid", ["qualified sensors and sampling", "historian/DAQ", "laboratory turnaround model", "alarm/action criteria"], "Execute CHEM-21 over repeated operating cycles, intentionally introduce permitted calibration shifts or benign fault simulations, and verify diagnostic logic, redundant/confirmatory measurements, sample-trigger criteria, operator response, data validation and recovery.", ["historian/analytics", "sensor health algorithms", "LIMS interface", "alarm/HSI testbed"], ["cross-calibration model", "drift/failure detection thresholds", "alarm/response procedures", "data-quality flags"], "The system detects out-of-tolerance behavior before an incorrect chemistry or inventory decision and restores a qualified measurement without loss of control.", "HP-I4 monitoring strategy qualified"),
            step("INST-05", "Confirm radiation compatibility and release the qualification dossier.", "Instrumentation & Controls Engineer", ["Radiation Protection/Chemistry", "Fuel/Materials Engineer", "QA/Configuration Management"], "Authorized irradiation/hot-cell facility and project qualification organization", ["CHEM-22/23 data", "device materials/components", "radiation profiles", "surrogate qualification"], "Use coupon/component irradiation or authorized irradiated-salt exposure as required to confirm material, electronics, sensor, reference, sorbent/seal and sample-container performance. Reconcile with surrogate tests, define replacement/calibration intervals and issue procurement/installation/maintenance specifications.", ["authorized irradiation/hot-cell services", "post-exposure analysis", "EQ/qualification database", "EDMS"], ["radiation compatibility report", "instrument qualification files", "procurement specifications", "calibration/surveillance program", "approved limitations"], "Credited instruments and sampling systems have complete qualification, calibration, maintenance and configuration records for the claimed environment and mission.", "HP-I5 qualification release")
        ],
        decision_points=[
            decision("Credited online and confirmatory measurements", "Chemistry/I&C/MC&A/safety", "2027-06-30", "measurement requirements and uncertainty allocation"),
            decision("Instrument and sample-system down-select", "I&C/chemistry/operations", "2028-03-31", "bench and loop qualification report"),
            decision("Commercial qualification and replacement strategy", "I&C/design authority", "2031-12-31", "radiation/integral evidence and qualification dossier"),
        ],
        task_specific_test_ids=["CHEM-06", "CHEM-07", "CHEM-20", "CHEM-21", "CHEM-22", "CHEM-23", "CHEM-24"],
    )

    # Material control and accountancy.
    t = find_task(db, "S-MSR-06")
    update_plan(
        t,
        implementation_summary="Implement liquid-fuel MC&A by defining material balance areas and key measurement points, qualifying mass/volume/composition and secondary-inventory measurements, validating a dynamic inventory model with surrogate and fuel batches, exercising anomaly detection and confirming the approach during the INL experiment and demonstrator.",
        implementation_steps=[
            step("MCA-01", "Define material balance areas, inventory locations, transfers and reporting obligations.", "Safeguards/Security Engineer", ["Radiation Protection/Chemistry", "Fuel/Materials Engineer", "Systems Engineer", "Operations Engineer"], "Project safeguards/systems organization", ["fuel ownership and authority", "P&IDs and process architecture", "receipt/storage/transfer plan", "regulatory/DOE safeguards requirements"], "Map every authorized inventory location and pathway: receipt packages, storage, preparation/loading, primary salt, drain tanks, gas train, deposits, filters/sorbents, samples, processing equipment, heels, scrap, waste and returned material. Define material balance areas, key measurement points, transfer boundaries, record owners and reporting clocks.", ["data-centric P&IDs", "MC&A requirements database", "inventory-location register"], ["MC&A concept of operations", "MBA/KMP map", "measurement and record requirements", "reporting matrix"], "No credible material location or transfer exists outside the controlled inventory map and responsibilities are accepted by the host/authority.", "HP-A1 MC&A architecture freeze"),
            step("MCA-02", "Develop measurement methods and uncertainty model.", "Radiation Protection/Chemistry", ["Safeguards/Security Engineer", "Instrumentation & Controls Engineer", "Data/Software Engineer"], "Qualified measurement/analytical laboratories and test facilities", ["inventory map", "instrument/sampling architecture", "batch specifications", "reporting detection goals"], "Define and qualify independent measurements for package/batch mass, isotopic/chemical composition, tank/loop inventory, samples, gas, deposits, filters/sorbents and waste. Build the measurement error model including correlations, hold-up, density/temperature conversion, sampling and laboratory uncertainty.", ["calibrated scales/load cells", "level/volume measurement", "qualified analytical methods", "uncertainty/UQ tools"], ["measurement qualification reports", "measurement-control program", "uncertainty model", "calibration/sampling procedures"], "The measurement system supports required inventory difference and anomaly-detection performance with documented uncertainty and fallback methods.", "HP-A2 measurement system qualified"),
            step("MCA-03", "Build and verify the dynamic inventory/accountancy model.", "Data/Software Engineer", ["Safeguards/Security Engineer", "Radiation Protection/Chemistry", "Systems Engineer"], "Project data/safeguards organization", ["MBA/KMP map", "process dynamic model", "measurement uncertainty", "operating modes and transfer procedures"], "Implement time-dependent inventory tracking across salt, gas, deposits, samples and secondary streams. Reconcile conserved elements/isotopes, uncertainty, decay/generation where applicable and configuration changes. Verify with independent calculations and simulated transfers before connection to operational data.", ["controlled inventory software", "historian/LIMS interfaces", "RAVEN/Python UQ", "configuration control/CI"], ["dynamic accountancy model", "verification/gold cases", "user/admin procedures", "cyber/data integrity controls"], "The model exactly reconciles controlled test cases, flags inconsistent data and preserves an auditable calculation trail.", "HP-A3 accountancy model release"),
            step("MCA-04", "Validate receipt, transfer, sampling, processing and waste balances with surrogate and qualification batches.", "Safeguards/Security Engineer", ["Operations Engineer", "Radiation Protection/Chemistry", "Test/Commissioning Engineer"], "Fuel-salt preparation facility and integrated processing skid", ["approved procedures", "qualified measurements", "surrogate/qualification batch genealogy", "anomaly test plan"], "Execute complete receipt-to-disposition material balances including loading, circulation, drain/recovery, sample withdrawal, gas/filters/deposits, processing residues and waste. Perform controlled discrepancy/anomaly exercises, loss-of-data recovery and physical inventory simulations; reconcile all secondary streams.", ["integrated skid/loop", "MC&A system", "sampling/analysis", "weighed filters/sorbents and deposits"], ["batch balance reports", "anomaly-exercise records", "procedure revisions", "uncertainty/detection performance"], "Inventory balances close within approved uncertainty, known hold-up is characterized, and the system detects and resolves preplanned discrepancies.", "HP-A4 surrogate validation"),
            step("MCA-05", "Integrate authorized fuel production, transport, receipt and host records.", "Safeguards/Security Engineer", ["Procurement/Supply Chain", "Radiation Protection/Chemistry", "Host/DOE Interface Lead"], "Supplier, carrier, host receipt and storage locations", ["DOE/supplier ownership terms", "shipping package records", "production genealogy", "host receipt authorization"], "Define data and custody handoffs from enrichment/deconversion/synthesis through packaging, transport, receipt, storage and loading. Verify seals, quantities, assays, sample/reference identifiers, waste/residue ownership, return/disposition and record retention; rehearse receipt and discrepancy workflows before shipment.", ["supplier/host MC&A systems", "secure transmittal/EDMS", "receipt inspection equipment", "chain-of-custody controls"], ["end-to-end genealogy", "shipping/receipt reconciliation", "custody transfer records", "discrepancy procedures"], "Supplier, DOE, carrier and host records reconcile without unexplained difference and the receiving inventory baseline is formally accepted.", "HP-A5 fuel receipt baseline"),
            step("MCA-06", "Confirm performance during the INL experiment and demonstrator and issue operating program.", "Safeguards/Security Engineer", ["Operations Engineer", "Radiation Protection/Chemistry", "Data/Software Engineer", "QA/Configuration Management"], "INL critical experiment and demonstrator", ["qualified model/procedures", "real operating data", "fission-product/secondary inventory models", "reporting plan"], "Run material balances through criticality, power changes, sampling, chemistry processing, drain/recovery and planned experiments. Compare predicted and measured gas/deposit/filter/sample inventories, resolve anomalies, update uncertainty and issue the operating surveillance, physical-inventory and reporting program.", ["operational MC&A system", "historian/LIMS", "sampling/off-gas data", "controlled reporting workflow"], ["INL and demonstrator validation reports", "final MC&A program/procedures", "training/qualification", "regulatory/DOE evidence"], "Program meets host/authority requirements and demonstrates reliable, auditable inventory control through representative operating evolutions.", "HP-A6 operating program release")
        ],
        decision_points=[
            decision("Material balance areas and key measurement points", "Safeguards/host/chemistry/systems", "2027-06-30", "approved MC&A architecture"),
            decision("Required anomaly-detection and inventory-difference performance", "Safeguards/authority", "2027-09-30", "measurement control and uncertainty requirements"),
            decision("MC&A approach adequate for demonstrator fuel receipt", "Host/safeguards/design authority", "2028-09-30", "surrogate validation and receipt readiness report"),
        ],
        task_specific_test_ids=["CHEM-01", "CHEM-03", "CHEM-19", "CHEM-20", "CHEM-23", "CHEM-24", "CHEM-25"],
    )

    # Materials/code/ISI basis.
    for task_id, prefix, focus in [
        ("S-MSR-09", "MAT", "commercial methods, code cases, surveillance and inservice inspection"),
        ("D-RD-02", "DMAT", "demonstrator material and joining down-select"),
        ("S-MTH-05", "MMTH", "materials/corrosion/irradiation topical methods"),
    ]:
        t = find_task(db, task_id)
        update_plan(
            t,
            implementation_summary=f"Qualify salt-wetted base metals, weldments, coatings, seals and nonmetallics for {focus} using traceable material heats, controlled chemistry, static and flowing exposures, thermal gradients, fission-product/impurity perturbations, mechanical and microstructural examinations, irradiation confirmation where needed, and repair/inspection demonstrations.",
            implementation_steps=[
                step(f"{prefix}-01", "Freeze materials, joining details, environments, degradation modes and acceptance metrics.", "Fuel/Materials Engineer", ["Mechanical Engineer", "Radiation Protection/Chemistry", "Structural/Civil Engineer"], "Project materials/design organization", ["salt chemistry/property envelope", "temperature/flow/stress/radiation profiles", "component life and code classification", "manufacturing/repair concepts"], "Create a specimen and component matrix with traceable heats, product forms, weld procedures/HAZ, coatings, seals, graphite/ceramics, stress states, chemistry/impurity/fission-product conditions and examination plan. Define acceptance for mass change, penetration, selective attack, cracking, strength/ductility, creep/fatigue, dimensional stability, leak tightness, inspectability and repairability.", ["materials requirements database", "degradation-mode/PIRT matrix", "codes/standards library"], ["materials qualification plan", "specimen/component matrix", "acceptance metrics", "surveillance/PIE plan"], "All credited materials and joints have a test or accepted data basis covering their limiting environment and life.", f"HP-{prefix}1 materials test matrix"),
                step(f"{prefix}-02", "Procure traceable materials and qualify specimen/joint preparation.", "Procurement/Supply Chain", ["Fuel/Materials Engineer", "QA/Configuration Management", "Supplier Quality"], "Qualified material suppliers and fabrication laboratory", ["material specifications", "WPS/PQR and joining requirements", "sample genealogy", "inspection plan"], "Procure representative heats and production-like product forms, produce weldments/joints/coatings/seals with controlled travelers, verify chemistry/microstructure/mechanical baselines and retain witness material. Do not substitute heats/processes without impact evaluation.", ["supplier QA records", "WPS/PQR/NDE", "baseline microscopy/mechanical testing", "EDMS"], ["material certificates and genealogy", "fabrication travelers", "baseline characterization", "accepted specimen inventory"], "Material identity, fabrication history and baseline condition are complete and representative of proposed production.", f"HP-{prefix}2 specimens accepted"),
                step(f"{prefix}-03", "Execute static chemistry and localized-attack screening.", "Fuel/Materials Engineer", ["Radiation Protection/Chemistry", "Independent Laboratory"], "Qualified controlled-atmosphere corrosion laboratory", ["accepted specimens", "CHEM-08 protocol", "salt/impurity/redox matrix", "analytical plan"], "Run replicate static exposures across composition, temperature, redox, impurities and surrogate fission-product groups. Characterize mass change, dissolved alloy constituents, surface/cross-section attack, grain-boundary/HAZ behavior and deposit chemistry; include blanks/reference coupons and post-exposure mechanical tests as required.", ["sealed capsules/crucibles", "controlled-atmosphere systems", "ICP/surface analysis", "metallography/SEM/EDS", "mechanical test equipment"], ["CHEM-08 qualified dataset", "corrosion rates/morphology", "chemistry-material interaction model", "down-select record"], "Materials failing localized attack, compatibility or retained-property criteria are removed or assigned explicit restrictions before loop/component testing.", f"HP-{prefix}3 static down-select"),
                step(f"{prefix}-04", "Execute flowing, thermal-gradient and mass-transfer tests.", "Fuel/Materials Engineer", ["Thermal-Hydraulics Engineer", "Radiation Protection/Chemistry", "Test/Commissioning Engineer"], "Materials flow loop/ITHF", ["static down-select", "CHEM-09/10 protocols", "representative velocity/temperature gradient", "production joining details"], "Expose coupons and component details in flowing salt with representative thermal gradients and chemistry control. Measure dissolution in hot sections, deposition in cold sections, erosion/cavitation/fretting where relevant, weld/seal performance, plugging/fouling and response to thermal cycles. Maintain a full salt/specimen/deposit mass balance.", ["materials test loop/ITHF", "corrosion/chemistry monitoring", "removable coupon racks", "NDE and leak testing", "DAQ"], ["CHEM-09/10 datasets", "component/weld qualification", "mass-transfer model", "inspection/maintenance observations"], "Predicted life and inspection/maintenance intervals retain required margin and no unresolved degradation mode threatens boundary integrity or function.", f"HP-{prefix}4 flowing qualification"),
                step(f"{prefix}-05", "Evaluate fission-product, irradiation and aging effects.", "Fuel/Materials Engineer", ["Radiation Protection/Chemistry", "Reactor Physicist", "Authorized Lab Interface Lead"], "Authorized surrogate, irradiation and hot-cell facilities", ["CHEM-11/12/22/23 data", "radiation/dpa/temperature profiles", "candidate materials", "PIE plan"], "Use stable fission-product surrogates first, then authorized irradiation/irradiated-salt specimens only where the safety/life claim cannot be closed otherwise. Examine segregation, transmutation/radiation effects, embrittlement, swelling, coating/seal response, deposit adhesion and post-irradiation properties.", ["surrogate corrosion tests", "authorized irradiation capsules", "hot-cell PIE", "microscopy/mechanical/NDE methods"], ["irradiation/PIE reports", "surrogate applicability assessment", "aging model parameters", "material restrictions"], "Radiation/fission-product effects are bounded in the life model or addressed through material/design/surveillance changes.", f"HP-{prefix}5 irradiation basis"),
                step(f"{prefix}-06", "Qualify inspection, surveillance, decontamination and repair methods.", "Mechanical Engineer", ["Fuel/Materials Engineer", "NDE/ISI Specialist", "Operations Engineer", "Radiation Protection/Chemistry"], "Component mockup, ITHF and qualified NDE/repair facilities", ["degradation morphology", "component geometry/access", "dose/contamination conditions", "candidate NDE/repair techniques"], "Demonstrate detection thresholds on representative flaws/deposits, coupon retrieval and trending, remote access, cleaning/decontamination, seal/component replacement and approved repair/joining methods. Define baseline examinations, periodic surveillance and acceptance/disposition rules.", ["UT/ET/visual/other NDE as applicable", "remote tooling/mockups", "decontamination rigs", "repair welding/brazing/seal procedures"], ["NDE/repair qualification", "surveillance coupon program", "inspection plan", "maintenance dose/time evidence"], "Inspection can detect relevant degradation before loss of function, and credible repair/replacement can be executed within the operating and radiological constraints.", f"HP-{prefix}6 ISI/repair qualification"),
                step(f"{prefix}-07", "Issue the material life, code, procurement and operating basis.", "Fuel/Materials Engineer", ["Mechanical Engineer", "Licensing Engineer", "QA/Configuration Management", "Operations Engineer"], "Project design/licensing organization", ["qualified datasets", "life models", "codes/standards gaps", "surveillance/repair qualifications"], "Release material specifications, allowable environmental/chemistry limits, design fatigue/creep/corrosion allowances, code-case/alternative requests, procurement and fabrication clauses, inspection/surveillance program, acceptance criteria and model/topical documentation. Establish triggers for requalification when salt, material, weld or operating conditions change.", ["controlled materials database", "life prediction/UQ", "codes/standards matrix", "EDMS/requirements traceability"], ["materials qualification report/topical", "procurement/fabrication specifications", "code/alternative packages", "ISI/surveillance program", "conditions of use"], "All credited components have a traceable material/fabrication/life/inspection basis and open code or data gaps have approved closure controls.", f"HP-{prefix}7 materials baseline release")
            ],
            decision_points=[
                decision("Material/joining down-select for demonstrator procurement", "Materials/mechanical/design authority", "2027-09-30", "static and preliminary loop qualification"),
                decision("Material life and surveillance basis adequate for commercial design", "Materials/licensing/design authority", "2031-12-31", "flowing, irradiation and inspection qualification"),
            ],
            task_specific_test_ids=["CHEM-08", "CHEM-09", "CHEM-10", "CHEM-11", "CHEM-12", "CHEM-17", "CHEM-22", "CHEM-23", "CHEM-24", "CHEM-25"],
        )

    # INL data/model release.
    t = find_task(db, "S-INL-19")
    update_plan(
        t,
        implementation_summary="Convert the INL critical experiment from raw operating data into qualified design and licensing evidence by freezing pre-test predictions, controlling the as-tested configuration, qualifying the data and uncertainty, comparing independent models, closing discrepancies, updating methods/uncertainties and releasing an approved data package with explicit conditions of use.",
        implementation_steps=[
            step("INL-DATA-01", "Freeze predictions, validation metrics and comparison protocol before data release.", "Reactor Physicist", ["Thermal-Hydraulics Engineer", "Radiation Protection/Chemistry", "Data/Software Engineer"], "Project/INL analysis teams", ["approved test matrix", "as-designed configuration", "code/model baselines", "measurement uncertainty plan"], "Run independent neutronics, kinetics, thermal, chemistry/source-term and MC&A predictions, seal the inputs/results and define comparison metrics, acceptance bands and discrepancy categories before the experiment results are shared with model developers.", ["qualified code suites", "secure prediction archive", "validation metric scripts"], ["frozen prediction packages", "comparison protocol", "configuration/model crosswalk"], "Predictions are reproducible, independently reviewed and frozen before measured results are released.", "HP-ID1 blind prediction freeze"),
            step("INL-DATA-02", "Establish the as-tested configuration and data provenance package.", "Test/Commissioning Engineer", ["INL/Host Interface Lead", "Data/Software Engineer", "QA/Configuration Management"], "INL experiment site and project data room", ["turnover/configuration records", "test logs", "calibration certificates", "material genealogy"], "Reconcile drawings, software/firmware, instrument serials/calibrations, fuel/salt batch, temperatures/flows, operator actions, exceptions and timing. Create an immutable as-tested configuration snapshot and master channel/sample dictionary.", ["EDMS/configuration system", "historian/DAQ", "calibration system", "sample/LIMS records"], ["as-tested configuration baseline", "channel/sample dictionary", "data provenance and exception log"], "Every released datum is traceable to an approved channel/sample, calibration, configuration and test event.", "HP-ID2 configuration/data provenance accepted"),
            step("INL-DATA-03", "Qualify raw data, samples and measurement uncertainty.", "Data/Software Engineer", ["Radiation Protection/Chemistry", "Reactor Physicist", "Independent Reviewer"], "INL/project data qualification team", ["raw native data", "sample results", "calibration/OOT records", "uncertainty models"], "Perform time alignment, range/status checks, calibration corrections, uncertainty propagation, sample/laboratory reconciliation, missing-data and outlier treatment, and independent review. Preserve raw data unchanged and document every transformation in executable scripts.", ["qualified Python/R workflow", "historian export", "LIMS", "version control/CI"], ["qualified dataset", "measurement uncertainty report", "data transformation scripts", "exception/disposition record"], "Dataset passes completeness, traceability, uncertainty and independent-review criteria for its intended validation use.", "HP-ID3 qualified data release"),
            step("INL-DATA-04", "Compare predictions, diagnose discrepancies and update models.", "Safety Analysis Engineer", ["Reactor Physicist", "Thermal-Hydraulics Engineer", "Radiation Protection/Chemistry", "Data/Software Engineer"], "Joint project/INL model validation workshop", ["frozen predictions", "qualified data", "validation metrics", "model uncertainty"], "Calculate metric-by-metric comparisons and integral balances, distinguish data/configuration/model discrepancies, perform controlled sensitivity studies and update models only through approved change records. Retest or perform confirmatory analysis when the discrepancy changes a safety, design or licensing conclusion.", ["validation metric/UQ tools", "code repositories", "issue/CAP system", "requirements traceability"], ["comparison report", "discrepancy cause/disposition", "updated model and uncertainty", "retest/confirmatory actions"], "All safety-significant discrepancies are resolved, bounded or explicitly carried as a condition of use with approved impact evaluation.", "HP-ID4 discrepancy closure"),
            step("INL-DATA-05", "Release design/licensing data and update downstream products.", "Chief Engineer/Design Authority", ["Licensing Engineer", "Safety Analysis Engineer", "Data/Software Engineer", "QA/Configuration Management"], "Project design authority and records system", ["qualified data", "validated model release", "discrepancy closures", "data rights/publication restrictions"], "Approve the data package, parameter updates, uncertainty reductions, conditions of use and downstream impact matrix. Update topical reports, demonstrator/commercial requirements, safety analyses, fuel/chemistry/MC&A bases and source-term inputs; publish only the authorized data subset.", ["EDMS and data repository", "requirements impact tools", "controlled authoring", "release approval workflow"], ["approved design-data release", "updated methods/parameters", "downstream impact/closure matrix", "public/proprietary release set"], "All identified downstream users acknowledge the new baseline and affected controlled products are updated or have approved change plans.", "HP-ID5 design-data release")
        ],
        decision_points=[
            decision("INL dataset qualified for each claimed use", "Data qualification/independent review", "2030-03-31", "qualified data release memo"),
            decision("Model discrepancies closed for demonstrator/commercial use", "Methods/design authority", "2030-06-30", "validation and discrepancy closure report"),
        ],
    )

    # Commercial fuel/material scaling.
    t = find_task(db, "P-PKG-02")
    update_plan(
        t,
        implementation_summary="Convert demonstrator/INL evidence into a production-ready commercial fuel and materials supply chain: freeze initial-core and makeup demand, reserve enrichment/deconversion/synthesis and analytical capacity, qualify the production facility and first-article batches, close materials/irradiation and licensing evidence, qualify alternate suppliers and demonstrate shipment, receipt, storage and load readiness before 2035 operation.",
        implementation_steps=[
            step("CFUEL-01", "Freeze commercial initial-core, makeup and contingency fuel requirements.", "Reactor Physicist", ["Fuel/Materials Engineer", "Radiation Protection/Chemistry", "Safeguards/Security Engineer", "Operations Engineer"], "Project commercial fuel organization", ["commercial core design", "operating/fuel-management strategy", "chemistry/material limits", "licensing and MC&A requirements"], "Issue commercial Fuel Material Requirements and Demand Forecast covering assay/form, mass, composition, batch/lot architecture, makeup cadence, reserve stock, impurities/redox, physical properties, packaging, ownership, sampling, acceptance, MC&A, waste and end state. Reconcile independently to core physics, chemistry and operating inventory models.", ["neutronics/fuel-management models", "chemistry/property database", "MC&A model", "requirements database"], ["commercial fuel requirements", "demand/capacity forecast", "ownership/disposition strategy", "independent reconciliation"], "Requirements support supplier contracting and licensing without an unresolved parameter that changes enrichment, deconversion, synthesis or facility design.", "HP-CF1 commercial fuel requirements freeze"),
            step("CFUEL-02", "Reserve enrichment, deconversion, synthesis, analytical, packaging and transport capacity.", "Procurement/Supply Chain", ["Fuel/Materials Engineer", "Safeguards/Security Engineer", "Legal/Commercial", "Supplier Quality"], "Qualified domestic suppliers and authorized fuel facilities", ["demand forecast", "supplier market survey", "DOE allocation/commercial experience", "delivery schedule"], "Issue RFIs/RFPs and negotiate capacity reservations/options for each transformation step. Require schedule, assay/form capability, quality/MC&A/security, data rights, reference samples, contingency/alternate capacity, price escalation and delay remedies. Maintain at least one credible alternate for the most schedule-critical step.", ["supplier portal/RFP", "capacity and schedule model", "commercial evaluation", "supplier audit tools"], ["capacity reservation agreements", "source selection records", "supply risk register", "alternate-route plan"], "Contracted capacity and delivery milestones support fuel receipt before startup with quantified schedule margin and a viable contingency route.", "HP-CF2 capacity secured"),
            step("CFUEL-03", "Qualify the commercial synthesis and analytical facility.", "Fuel/Materials Engineer", ["Radiation Protection/Chemistry", "Supplier Quality", "Safeguards/Security Engineer", "Licensing Engineer"], "Selected authorized fuel-salt production facility", ["fuel requirements", "demonstrator synthesis evidence", "facility authorization", "quality/MC&A programs", "process hazard analysis"], "Audit authorization, equipment, criticality/chemical safety, atmosphere/contamination controls, batch/material flow, sampling, analytical methods, calibration, MC&A, waste, cybersecurity/data and personnel qualifications. Execute production-scale surrogate and authorized qualification batches before first fissile commercial batch.", ["facility audit/surveillance", "process travelers", "analytical/LIMS", "MC&A system", "hazard review"], ["facility qualification report", "approved production/control plan", "analytical method qualification", "supplier corrective-action closure"], "Facility demonstrates repeatable, controlled production and complete genealogy at the commercial batch scale under the required authority and quality program.", "HP-CF3 production facility qualified"),
            step("CFUEL-04", "Produce and accept first-article commercial batches.", "Radiation Protection/Chemistry", ["Fuel/Materials Engineer", "Safeguards/Security Engineer", "Independent Laboratory", "Supplier Quality"], "Commercial fuel-salt facility and independent analytical laboratory", ["qualified facility/process", "feed certificates", "approved traveler/sampling", "acceptance specification"], "Produce first-article batches under source surveillance, reconcile feed/product/samples/residue/waste, verify isotopic and chemical homogeneity, impurities/redox, phase and selected properties, perform independent confirmatory analysis and retain reference samples. Resolve any off-specification condition through controlled disposition and repeat qualification if it changes the process.", ["production equipment", "qualified analytical suite", "calibrated mass/accountability", "source surveillance"], ["first-article batch records", "independent acceptance results", "material balance", "process capability metrics", "retained samples"], "Consecutive first-article batches meet specification and process capability/uncertainty criteria without unresolved material-accountability or chemistry anomaly.", "HP-CF4 first-article acceptance"),
            step("CFUEL-05", "Complete commercial materials, irradiation, life and inspection qualification.", "Fuel/Materials Engineer", ["Mechanical Engineer", "Radiation Protection/Chemistry", "NDE/ISI Specialist", "Authorized Lab Interface Lead"], "Qualified corrosion loops, irradiation/hot-cell and component test facilities", ["demonstrator/INL data", "commercial material/joint selections", "life/environment profiles", "surveillance/repair strategy"], "Close the material/joining matrix using long-duration flow/thermal-gradient, fission-product/impurity, irradiation/PIE and component/repair/inspection evidence. Fit life models with uncertainty and release surveillance coupon, ISI, chemistry-limit and repair/replacement programs.", ["materials loops/ITHF", "irradiation/PIE services", "mechanical/metallographic/NDE testing", "life model/UQ"], ["commercial materials qualification report", "life/allowables", "inspection/surveillance program", "code/alternative evidence", "procurement clauses"], "Commercial component life and detect/repair strategy retain required margin over the licensed interval and all material restrictions are flowed to design and operations.", "HP-CF5 materials qualification complete"),
            step("CFUEL-06", "Demonstrate packaging, transport, receipt, storage and loading interfaces.", "Safeguards/Security Engineer", ["Procurement/Supply Chain", "Operations Engineer", "Radiation Protection/Chemistry", "Host/Site Interface Lead"], "Supplier, carrier and commercial plant receipt/storage areas", ["accepted batch/package design", "transport authorization", "site fuel-handling design", "security/MC&A procedures"], "Complete package and shipment approvals, route/carrier/security planning, receipt inspection and custody transfer. Perform nonfuel/dummy package and transfer rehearsals, verify heating/storage limits, sampling, contamination control, criticality/material controls, emergency response, rejected package handling and loading handoff.", ["approved transport package", "receipt/transfer equipment", "weighing/sampling/survey instruments", "work management/MC&A"], ["transport and receipt readiness report", "rehearsal records", "approved procedures", "custody-transfer and storage baseline"], "Site can receive, verify, store and transfer accepted batches without violating authorization, chemistry, temperature, security, criticality or inventory controls.", "HP-CF6 fuel logistics readiness"),
            step("CFUEL-07", "Release licensing evidence and obtain production/startup readiness approval.", "Licensing Engineer", ["Fuel/Materials Engineer", "Reactor Physicist", "Safeguards/Security Engineer", "Operations Engineer", "QA/Configuration Management"], "Project licensing and design authority", ["fuel/material qualification", "supplier/facility approval", "transport/receipt evidence", "application commitments"], "Update FSAR/application/topicals, Technical Specifications/programs, criticality/MC&A/security, chemistry and startup documents. Reconcile commitments, inspections/ITAAC or verification evidence by licensing path, complete fuel-load readiness criteria and establish continuing supply/performance surveillance.", ["controlled authoring/EDMS", "requirements/commitment tracking", "readiness dashboard", "supplier performance system"], ["fuel/material licensing package", "production authorization", "fuel-load readiness evidence", "continuing supply and surveillance plan"], "Regulatory/authorization commitments are closed or controlled, accepted fuel is available before need, and the plant organization is ready to receive and load it.", "HP-CF7 commercial fuel readiness")
        ],
        decision_points=[
            decision("Commercial fuel chemistry/form and demand baseline", "Physics/chemistry/design authority", "2028-12-31", "approved commercial Fuel Material Requirements Specification"),
            decision("Production facility and capacity route", "Procurement/fuel/safeguards/executive", "2029-06-30", "capacity agreements and facility qualification plan"),
            decision("First-article production acceptance", "Fuel/chemistry/QA/MC&A/design authority", "2033-12-31", "accepted consecutive batches and capability report"),
            decision("Commercial fuel-load readiness", "Operations/licensing/design authority", "2035-03-31", "fuel-load readiness package and accepted inventory"),
        ],
        task_specific_test_ids=["CHEM-01", "CHEM-02", "CHEM-03", "CHEM-04", "CHEM-05", "CHEM-08", "CHEM-09", "CHEM-10", "CHEM-20", "CHEM-22", "CHEM-23", "CHEM-24", "CHEM-25"],
    )

    # Fuel receipt work packages for demonstrator and plant.
    for task_id, prefix, context, due in [
        ("D-3.14.f", "DFR", "demonstrator", "2029-03-31"),
        ("P-3.14.f", "PFR", "commercial plant", "2035-03-31"),
    ]:
        t = find_task(db, task_id)
        update_plan(
            t,
            implementation_summary=f"Execute the {context} fuel receipt and load-readiness process from pre-shipment document review through package receipt, identity/quantity/chemistry confirmation, storage and MC&A baseline, transfer rehearsal, authorization checks and formal handoff to fuel loading.",
            implementation_steps=[
                step(f"{prefix}-01", "Approve receipt, storage, sampling, MC&A, security and emergency procedures.", "Operations Engineer", ["Safeguards/Security Engineer", "Radiation Protection/Chemistry", "Radiation Protection", "QA/Configuration Management"], f"{context.title()} operations organization", ["fuel supply/ownership terms", "package and site design", "host/license requirements", "fuel acceptance specification"], "Write integrated procedures for pre-shipment release, notifications, access/security, package receipt, surveys, seal/identity/weight verification, storage, heating/temperature, sampling, MC&A entry, nonconformance/rejection, emergency response, transfer and load handoff. Identify hold/witness points and stop-work criteria.", ["work management/clearance", "MC&A system", "receipt inspection and survey equipment", "controlled procedures"], ["approved receipt/storage procedures", "RACI and communications plan", "readiness checklist"], "Procedures are walked down, interfaces accepted and no authorization or equipment prerequisite remains open.", f"HP-{prefix}1 procedure readiness"),
                step(f"{prefix}-02", "Verify supplier batch and shipping package before release.", "Fuel/Materials Engineer", ["Radiation Protection/Chemistry", "Safeguards/Security Engineer", "Supplier Quality"], "Fuel supplier and shipping origin", ["batch traveler/certificates", "independent analysis", "package approval", "shipping plan"], "Review genealogy, isotopic/chemical results, impurity/redox/phase/property data, material balance, samples, seals, package cleanliness/condition, contamination survey, temperature/heat requirements and shipment authorizations. Resolve discrepancies before shipping release.", ["supplier records/EDMS", "independent lab results", "shipping package records", "source surveillance"], ["shipment release checklist", "accepted certificates/data", "seal/package baseline", "open-item closure"], "Fuel batch and package meet specification and custody/accountability records reconcile before departure.", f"HP-{prefix}2 shipment release"),
                step(f"{prefix}-03", "Perform receipt inspection, custody transfer and storage baseline.", "Safeguards/Security Engineer", ["Operations Engineer", "Radiation Protection/Chemistry", "Radiation Protection", "QA/Configuration Management"], f"{context.title()} receiving and storage area", ["advance shipping notice", "package baseline", "receipt procedure", "calibrated equipment"], "Confirm carrier/route/notifications, inspect package and seals, conduct radiological/contamination and condition surveys, verify identity/quantity, witness transfer, take authorized confirmatory sample if required, enter MC&A, establish storage configuration/temperature and document custody/title transfer.", ["calibrated scales/survey instruments", "seal verification", "sampling equipment", "MC&A/work management"], ["receipt inspection report", "custody transfer", "MC&A entry", "storage baseline", "sample record"], "Package and contents are accepted or quarantined under an approved disposition; no unexplained quantity, identity, condition or authorization discrepancy remains.", f"HP-{prefix}3 receipt acceptance"),
                step(f"{prefix}-04", "Complete storage, transfer and loading rehearsals.", "Test/Commissioning Engineer", ["Operations Engineer", "Radiation Protection/Chemistry", "Safeguards/Security Engineer", "Human Factors Engineer"], f"{context.title()} storage/transfer systems", ["accepted package or representative dummy", "transfer equipment", "approved procedures", "instrument/calibration status"], "Rehearse access, connection, heating, inerting, transfer, sampling, drain/recovery, spill/leak response, material reconciliation, disconnect and contingency actions using nonfuel material or a representative dummy where practical. Verify operator communications, clearances, hold points and recovery from selected faults.", ["receipt/transfer equipment", "dummy package/surrogate", "simulator/mockup", "DAQ/work management"], ["rehearsal/test records", "procedure revisions", "equipment punch-list closure", "material-balance demonstration"], "Rehearsal completes within acceptance, equipment and procedures function as intended, and deviations are closed before fuel movement.", f"HP-{prefix}4 transfer readiness"),
                step(f"{prefix}-05", "Issue formal fuel-load readiness and transfer custody to the loading team.", "Chief Engineer/Design Authority", ["Operations Engineer", "Licensing Engineer", "Safeguards/Security Engineer", "QA/Configuration Management"], f"{context.title()} readiness review", ["accepted fuel/storage baseline", "system turnover", "authorization conditions", "staff qualifications", "emergency/contingency readiness"], "Verify all technical, authorization, equipment, procedure, personnel, security, criticality, chemistry, MC&A, radiation protection and records prerequisites. Review open items against explicit no-go criteria and issue an approved loading authorization/custody handoff.", ["readiness review checklist", "evidence index", "open-item/CAP tracker", "authorization basis"], ["fuel-load readiness report", "approved loading authorization", "custody handoff", "controlled open-item list"], f"Fuel loading is authorized by the required host/regulatory and technical authorities by {due}, with no unresolved no-go condition.", f"HP-{prefix}5 fuel-load authorization")
            ],
            decision_points=[
                decision("Shipment release", "Fuel/chemistry/MC&A/QA", due, "approved pre-shipment review"),
                decision("Fuel receipt acceptance", "Host operations/MC&A/QA", due, "receipt inspection and custody record"),
                decision("Fuel-load readiness", "Host/operations/design authority/licensing", due, "approved readiness report"),
            ],
        )

    # Demonstrator experiment task packages.
    demo_exp_specs = {
        "D-EXP-02": (
            "DEXI", "Qualify the demonstrator instrumentation, sampling, calibration, historian and data architecture before fuel operation.",
            [
                ("Freeze the experiment measurement and data-quality requirements.", "Create a channel/sample matrix linked to every test objective, uncertainty target, acceptance rule, model parameter and configuration state."),
                ("Complete sensor/sample/DAQ design and procurement.", "Specify ranges, accuracy, response, materials, environmental/radiation capability, calibration, time synchronization, sample custody, redundancy and spares; source-surveil critical equipment."),
                ("Integrate and commission the data chain end to end.", "Verify sensor-to-historian scaling, time alignment, software/firmware, calibration certificates, sample/LIMS links, cybersecurity, backups and immutable raw-data retention."),
                ("Execute dry/hot surrogate qualification and fault recovery.", "Run loops, simulated channels, representative-salt samples, drift/fault simulations, data loss/recovery and automated acceptance checks before fuel loading."),
                ("Issue the qualified data architecture and operating controls.", "Release channel dictionary, calibration/surveillance program, data qualification scripts, sample procedures, exception process and evidence index."),
            ],
            ["CHEM-06", "CHEM-20", "CHEM-21", "CHEM-22"],
        ),
        "D-EXP-04": (
            "DEXB", "Establish the initial fuel-salt chemistry, inventory and sample baseline during loading and first circulation.",
            [
                ("Approve the load/baseline plan and pre-load predictions.", "Define batch sequence, temperatures, inventory measurement, expected composition/redox/property values, sample locations/timing, acceptance bands and stop conditions."),
                ("Verify accepted fuel, systems, instruments and material-accountability readiness.", "Confirm batch/receipt records, clean/dry/inert system state, calibrations, drain/recovery, off-gas, sampling, secondary containment and authorization prerequisites."),
                ("Load and circulate in controlled increments.", "Record each transfer, mass/level/temperature, gas response, sample and configuration; reconcile inventory after each increment and stop for unexpected chemistry, leak, plugging or balance discrepancy."),
                ("Establish independent chemistry and property baseline.", "Compare online measurements with representative duplicate samples and independent laboratory analysis; verify composition, impurities/redox, homogeneity, phase behavior and selected properties."),
                ("Release the initial operating baseline.", "Approve starting chemistry limits, instrument offsets/uncertainty, material balance, retained samples, startup conditions and corrective actions before criticality/power tests."),
            ],
            ["CHEM-01", "CHEM-03", "CHEM-04", "CHEM-05", "CHEM-06", "CHEM-20", "CHEM-21"],
        ),
        "D-EXP-09": (
            "DEXC", "Execute the 2029 demonstrator chemistry/redox/impurity/sampling/fission-product behavior campaign under coupled nuclear and thermal conditions.",
            [
                ("Freeze the campaign matrix and blind predictions.", "Select operating plateaus and controlled perturbations, predefine chemistry/source-term model predictions, sample schedule, uncertainty, acceptance and recovery actions."),
                ("Establish stable baseline at each operating plateau.", "Hold configuration and power/temperature/flow long enough to close salt/gas/sample balances and demonstrate sensor/laboratory agreement before perturbations."),
                ("Execute authorized chemistry and impurity-response tests.", "Apply only preapproved bounded changes or operating evolutions; track redox, impurities, corrosion products, gas species, deposits and system response and recover to baseline."),
                ("Qualify sampling, online sensor and laboratory performance.", "Run duplicate samples, independent analyses, drift/fouling checks and sample-location comparisons; update calibration only through controlled change."),
                ("Release chemistry operating limits and model updates.", "Compare to predictions, quantify uncertainty, close discrepancies and issue updated chemistry limits, monitoring, procedures and commercial design inputs."),
            ],
            ["CHEM-06", "CHEM-07", "CHEM-11", "CHEM-20", "CHEM-21", "CHEM-24"],
        ),
        "D-EXP-10": (
            "DEXS", "Execute the mechanistic source-term, off-gas, retention, plate-out and release-path campaign.",
            [
                ("Freeze species groups, inventories, compartments and predictions.", "Define event/operating cases, expected gas/aerosol/deposit/filter inventories, sampling and measurement uncertainty before data release."),
                ("Characterize steady operating partitioning.", "Measure salt, cover gas, deposits, filters/sorbents and selected surfaces at stable plateaus and reconcile the mass/activity balance."),
                ("Execute bounded transients and treatment-function tests.", "Test approved changes in power/temperature/flow, gas handling, bypass or capture-media condition without compromising safety/authorization; measure transfer and retention response."),
                ("Inspect and characterize deposits, filters and components.", "Retrieve planned coupons/media/samples, preserve location and genealogy, perform radiochemical/surface analysis and quantify plate-out, capture, resuspension and waste inventories."),
                ("Validate the source-term model and release design inputs.", "Compare blind predictions, update transfer/retention uncertainty, close discrepancies and issue commercial source-term, shielding, off-gas, monitoring and waste inputs."),
            ],
            ["CHEM-11", "CHEM-12", "CHEM-13", "CHEM-14", "CHEM-15", "CHEM-16", "CHEM-17", "CHEM-23", "CHEM-24", "CHEM-25"],
        ),
        "D-EXP-12": (
            "DEXM", "Execute the materials, corrosion, component, pump, valve, instrument and surveillance campaign needed for commercial life and maintenance decisions.",
            [
                ("Freeze specimen/component inventory and baseline condition.", "Document material heats, welds, coatings, seals, dimensions, NDE, mechanical properties, installation location and predicted environment."),
                ("Operate planned exposure and duty cycles.", "Accumulate representative temperature, flow, chemistry, power, starts/stops, thermal cycles and component duty while preserving configuration and condition-monitoring data."),
                ("Retrieve and examine surveillance specimens/components.", "Perform controlled removal, decontamination, visual/NDE, dimensional, mass, surface/microstructure and mechanical examinations with full location/genealogy."),
                ("Demonstrate maintenance, replacement and repair.", "Execute selected pump/valve/instrument/seal/coupon changeouts or mockups, recording time, dose, tools, contamination, failure modes and recovery."),
                ("Update life, reliability and commercial surveillance basis.", "Compare predicted degradation and performance, fit life/reliability uncertainty, close anomalies and issue material limits, inspection intervals, spares and repair requirements."),
            ],
            ["CHEM-08", "CHEM-09", "CHEM-10", "CHEM-12", "CHEM-21", "CHEM-22", "CHEM-23", "CHEM-24", "CHEM-25"],
        ),
    }
    for task_id, (prefix, summary, actions, tests) in demo_exp_specs.items():
        t = find_task(db, task_id)
        steps = []
        for idx, (action, guidance) in enumerate(actions, start=1):
            steps.append(step(
                f"{prefix}-{idx:02d}", action, "Test/Commissioning Engineer",
                ["Radiation Protection/Chemistry", "Fuel/Materials Engineer", "Data/Software Engineer", "Operations Engineer"],
                "Demonstrator test organization and qualified laboratories",
                ["approved experiment/test matrix", "as-tested configuration", "qualified instruments/sampling", "pre-test predictions and uncertainty"],
                guidance,
                ["approved test procedure", "calibrated DAQ/historian", "sampling/LIMS", "qualified analysis scripts", "configuration and CAP systems"],
                ["approved readiness/test record", "raw and qualified data", "sample/material genealogy", "uncertainty and comparison report", "discrepancy dispositions"],
                "The step meets its preapproved acceptance and uncertainty criteria, preserves the configuration/data chain, and closes any exception before the next irreversible evolution.",
                f"HP-{prefix}{idx} test gate",
            ))
        update_plan(t, implementation_summary=summary, implementation_steps=steps, task_specific_test_ids=tests,
                    decision_points=[decision("Test readiness and configuration release", "Test director/operations/design authority", "2029-01-31", "approved readiness review"), decision("Qualified dataset and model/design credit", "Independent review/design authority", "2029-12-31", "qualified data release and discrepancy closure")])

    # Commercial operating optimization.
    t = find_task(db, "P-OPT-06")
    update_plan(
        t,
        implementation_summary="Optimize fuel utilization, circulating inventory, makeup, processing, sampling, consumables and waste only after establishing a controlled operating baseline; use reconciled mass/chemistry/economic data and validated models, pilot changes at bounded scale, evaluate licensing/MC&A/material impacts and implement through formal plant change control.",
        implementation_steps=[
            step("FOPT-01", "Establish baseline mass, chemistry, performance, waste and cost KPIs.", "Operations Engineer", ["Reactor Physicist", "Radiation Protection/Chemistry", "Safeguards/Security Engineer", "Cost Estimator"], "Commercial plant operations/performance organization", ["initial operating data", "MC&A balances", "chemistry/source-term/material surveillance", "fuel and waste contracts"], "Define a reconciled monthly/quarterly baseline for fuel utilization, reactivity value, circulating and secondary inventory, losses/hold-up, makeup, purification/capture media, sampling, waste volumes, worker effort/dose, downtime and unit costs. Require data-quality flags and uncertainty.", ["historian/LIMS/MC&A", "performance and cost analytics", "mass-balance model"], ["approved KPI baseline", "cost/mass/chemistry dashboard", "data-quality register"], "Baseline balances reconcile and are stable enough to distinguish an optimization effect from normal variability.", "HP-FO1 baseline accepted"),
            step("FOPT-02", "Identify and screen optimization opportunities.", "Fuel/Materials Engineer", ["Operations Engineer", "Reactor Physicist", "Radiation Protection/Chemistry", "Waste/Environmental Engineer"], "Plant engineering/performance organization", ["KPI baseline", "operating experience", "validated models", "supplier/waste constraints"], "Screen changes to operating inventory, makeup timing, chemistry band, sampling frequency, gas/filtration media, cleanup operation, residual-salt recovery, component life, waste conditioning and consumables. Evaluate safety/licensing, MC&A, criticality, materials, source term, maintainability, dose and economics before selecting candidates.", ["validated reactor/chemistry/source-term models", "cost-benefit and risk model", "requirements/impact analysis"], ["opportunity register", "technical/economic screening", "change-classification and test plan"], "Selected opportunities have positive risk-adjusted value and no unbounded safety, licensing, safeguards or material-life impact.", "HP-FO2 opportunity selection"),
            step("FOPT-03", "Demonstrate bounded changes in model, laboratory, skid or plant test.", "Test/Commissioning Engineer", ["Fuel/Materials Engineer", "Operations Engineer", "Data/Software Engineer", "Licensing Engineer"], "Validated models, qualified laboratory/skid and commercial plant under approved test", ["approved change/test plan", "pre-test predictions", "acceptance/abort criteria", "configuration baseline"], "Use the least hazardous and least disruptive evidence source first. Execute bounded laboratory/skid tests or controlled plant trials with measurement uncertainty, mass/chemistry balance, material/sensor response, operator workload and rollback criteria. Preserve blind prediction and qualified data practices.", ["qualified models", "chemistry/processing skid", "plant test procedure/DAQ", "CAP/change control"], ["test results", "qualified comparison", "rollback/exception records", "updated economics and uncertainty"], "Candidate change demonstrates required benefit and remains within approved safety/chemistry/material/MC&A and operating limits.", "HP-FO3 optimization evidence"),
            step("FOPT-04", "Approve and implement the plant change.", "Chief Engineer/Design Authority", ["Operations Engineer", "Licensing Engineer", "Safeguards/Security Engineer", "QA/Configuration Management"], "Commercial plant change-control organization", ["qualified evidence", "impact evaluation", "procedure/training changes", "regulatory/authorization determination"], "Complete engineering and licensing-basis change evaluation, supplier/material impact, MC&A/security, waste/transport, procedure, training, Technical Specification/program and configuration updates. Implement with hold points and post-change monitoring.", ["plant modification/change process", "requirements/EDMS", "work management/training", "regulatory screening"], ["approved plant change", "updated procedures/training/configuration", "implementation and post-change test record"], "Change is installed and verified under the applicable authorization with all affected controlled products updated.", "HP-FO4 change implementation"),
            step("FOPT-05", "Confirm sustained economics and standardize fleet feedback.", "Cost Estimator", ["Operations Engineer", "Fuel/Materials Engineer", "Reliability Engineer", "Data/Software Engineer"], "Plant performance and fleet engineering", ["post-change operating data", "baseline/KPIs", "maintenance/waste/fuel invoices", "reliability data"], "Monitor enough operating time to capture variability, component/capture-media life and maintenance effects. Compare realized cost, inventory, waste, dose, availability and safety performance to forecast; reverse or modify if benefits do not persist. Release lessons and standard design/operating changes.", ["performance analytics", "reliability and cost system", "fleet knowledge base"], ["post-implementation review", "realized savings/performance", "fleet standard or rollback decision", "updated models and estimate"], "Sustained benefits are demonstrated without degraded safety, reliability, materials, MC&A or licensing performance.", "HP-FO5 optimization closeout")
        ],
        decision_points=[
            decision("Optimization candidate selection", "Operations/engineering/fuel/chemistry", "2036-06-30", "risk-adjusted screening and approved test plan"),
            decision("Permanent implementation", "Design authority/operations/licensing", "2037-06-30", "qualified test evidence and change evaluation"),
        ],
    )

    # Update meta/data quality notes.
    db["meta"]["generated"] = "2026-08-18T05:00:00Z"
    db["data_quality"]["high_consequence_bespoke_implementation_tasks"] = 21
    db["data_quality"]["implementation_playbook_count"] = len(db.get("implementation_playbooks", {}))
    db["data_quality"]["chemistry_experiment_count"] = len(db.get("chemistry_processing_plan", {}).get("experiment_matrix", []))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--database", type=Path, default=DEFAULT_DB)
    args = parser.parse_args()
    db = json.loads(args.database.read_text(encoding="utf-8"))
    apply(db)
    args.database.write_text(json.dumps(db, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Updated high-consequence implementation plans in {args.database}")


if __name__ == "__main__":
    main()
